---
name: Install platforms
on: push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
        with:
          path: github.com/configs
      - name: Run installer
        run: |
          cd github.com/configs
          ./install.sh

  macos:
    runs-on: macos-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
        with:
          path: github.com/configs
      - name: Run installer
        run: |
          cd github.com/configs
          ./install.sh

  ###  Some installations need to be run in containers

  alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14
    # TODO Mount repo into container
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
        with:
          path: github.com/configs
      - name: Run installer
        run: |
          cat /etc/os-release

  archlinux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
    # TODO Mount repo into container
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
        with:
          path: github.com/configs
      - name: Run installer
        run: |
          cat /etc/os-release

  debian:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    # TODO Mount repo into container
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
        with:
          path: github.com/configs
      - name: Run installer
        run: |
          cat /etc/os-release
