---
name: Install platforms

on:
  push:
    paths:
      - 'install.sh'
      - '.github/workflows/build.yaml'

env:
  CONTAINER_HOME: '/github/home/work/configs/configs'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
        with:
          path: github.com/configs
      - name: Run installer
        run: |
          cd github.com/configs
          ./install.sh --all
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

  macos:
    runs-on: macos-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
        with:
          path: github.com/configs
      - name: Run installer
        run: |
          cd github.com/configs
          ./install.sh --all

  ###  Some OS installations need to be run in containers

  alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14
      volumes:
        # mount our configs into the correct path in the container
        - /home/runner/work/configs/configs/:/github/home/work/configs/configs
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
        with:
          path: github.com/configs
      - name: Run installer
        run: |
          apk add --no-cache bash
          cd ${CONTAINER_HOME}/github.com/configs
          ./install.sh --all
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

  archlinux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      volumes:
        # mount our configs into the correct path in the container
        - /home/runner/work/configs/configs/:/github/home/work/configs/configs
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
        with:
          path: github.com/configs
      - name: Run installer
        run: |
          cd /github/home/work/configs/configs/github.com/configs
          ./install.sh --all

  debian:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
      volumes:
        # mount our configs into the correct path in the container
        - /home/runner/work/configs/configs/:/github/home/work/configs/configs
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
        with:
          path: github.com/configs
      - name: Run installer
        run: |
          cd /github/home/work/configs/configs/github.com/configs
          ./install.sh --all
